### ISSUE TITLE
Download expiry for getfilelink() URL

### ISSUE THREAD

**Issue by whitsey** [ivankrastev26/pcloud-php-sdk#14]
Uploaded a file. Used getfilelink(fileId)  to generate link
Link worked fine yesterday
Today I get "Your download expired. Try previous step again."
How do I fix this? How to extend expiry time? 
The only options are:

```
forcedownload | int Download with Content-Type = application/octet-stream
contenttype | string Set Content-Type
maxspeed | int limit the download speed
skipfilename | int include the name of the file in the generated link
```

**Comment by sich** [comment]
Every time you need to download a file you have to call getfilelink and use the link immediately. All our clients work that way. This is bacause files are being stored on different storage servers and they could be moved.
