### ISSUE TITLE
One-step token

### ISSUE THREAD

**Issue by icomenezes** [ivankrastev26/pcloud-php-sdk#17]
Guys, good afternoon! There is some method that already returns the TOKEN direct to me. Without I having to authorize through the site? I wanted to order and receive the token without needing a second screen.
thankful

**Comment by pollux1er** [comment]
I guess no because from my own, it is the only way to obtain the token. But my question is : is the token lifetime ?
If yes, then we can get it once and use it forever in an app...

**Comment by theroot79** [comment]
Hello @icomenezes  and @pollux1er  , so far we don't plan to provide an option for direct generation of access_token, your will have to go through the oauth validation process. 
The access tokens doesn't expire.
