### ISSUE TITLE
uploadprogress : Upload not found

### ISSUE THREAD

**Issue by JeanLouisMassei** [ivankrastev26/pcloud-php-sdk#27]
Hi,

Cant find out how to use the uploadProgress feature.

Here I upload my file : 
$pcloudFile = new pCloud\Sdk\File($pCloudApp);
$pcloudFile->upload($fileName, $folderId, $fileName, 0, "myHash");

And in an another thread I try to get the status of the upload : 
$request = new pCloud\Sdk\Request($pCloudApp);
$tmp = $request->get("uploadprogress", ['progresshash' => "myHash"]);
$tmp = $tmp->uploaded;

I get this error : 
Uncaught pCloud\Sdk\Exception: Upload not found in ....

Should I use the hash provided by the upload function ? Well actually I get the same error even when using this hash : 
$hash = $pcloudFile->upload($fileName, $folderId);
$hash = $hash->metadata->hash;

Thank you for your help,

**Comment by theroot79** [comment]
Hello JeanLouisMassei,
somewhere at the end of the example script, which you provided you are executing the following code: 

`$hash = $pcloudFile->upload($fileName, $folderId);`

which is doing something which we call "chunked upload", the PHP script actually is sending the file on chunks using "upload_write" method. This method currently doesn't supply/has info related to the "uploadprogress", the "uploadprogress" currently is supported only by the standard "uploadfile" API endpoin. This is one of the reasons you can not fetch info related to the progress of the upload, on the other hand you also need to supply the "uploadprogress" API call with the exact API server the upload is happening on, which I can not see in the example. In any case we are planning in the future to add support for upload progress also to the "upload_write" API call, and of course we will add additional methods to the SDK, so it can be easy utilized.

**Comment by theroot79** [comment]
In addition, you can implement and use the following method "/upload_info with access_token=$auth&uploadid=1234 as params, which will return: 
`{ 
"result": 0, 
"size": 150000000, 
"sha256": "0469c985af64834db8c5dd411bf44af83d0b0a9e6852ab1de7925af0bdc18e24",
"sha1": "cf068822a61029b57378fe75d051817f714c24e7"
}`
where the **size** ( in bytes ) is what you need.
