### ISSUE TITLE
Wrong path renaming on upload

### ISSUE THREAD

**Issue by matthieuuu** [ivankrastev26/pcloud-php-sdk#28]
Hey team!

I don't understand why you're replacing '_' with the directory separator. I got '_' character in my folder's name that is replaced by a '/' (in my case) so the all path is wrong and I cannot upload any file.

https://github.com/pCloud/pcloud-sdk-php/blob/61fb9b98ca2db11ead4423ef16ce0ac5ea16225b/lib/File.php#L120

Could you please fix it?
Thank you

**Comment by theroot79** [comment]
We are preparing fix, will be released in the next few days.
