### ISSUE TITLE
Laravel integration

### ISSUE THREAD

**Issue by LucaF87** [ivankrastev26/pcloud-php-sdk#29]
Hi,
If possible to use PcCloud with Laravel Storage ?
Laravel documentation https://laravel.com/docs/10.x/filesystem#custom-filesystems

Thanks

**Comment by fardeenkhan7337** [comment]
you have to first save the large files by using laravel-chunk if you want to save large files otherwise just it as your saving the other files like user images and then get the file and upload it on pCloud by using pCloud upload method

**Comment by theroot79** [comment]
Hello @LucaF87 , we're currently evaluating the potential development of a Laravel storage module. We'll make sure to update you here once we have any news or developments to share. Thank you for your interest!

**Comment by LucaF87** [comment]
Hi, I finally thought of it ;)

https://github.com/LucaF87/flysystem-pcloud

**Comment by theroot79** [comment]
Hello @LucaF87 
your dedication to creating this is truly admirable, we deeply value the effort you've invested. if you need any assistance to further support and enhance it, we will be happy to assist, don't hesitate to reach out.
