### ISSUE TITLE
Can´t create a new app

### ISSUE THREAD

**Issue by TSerra-PT** [ivankrastev26/pcloud-php-sdk#31]
Hello guys,

I am trying to create a "New App" to get the App Key, App Secret and Redirect URIs but it gaves me this error:

![imagem](https://github.com/pCloud/pcloud-sdk-php/assets/11211940/7e9991d4-806a-4737-92e9-b1f8cc47c7ca)

Can anyone help me in this process?

**Comment by xiconet** [comment]
I have the same problem, why is this issue closed without any explanation ?
