### ISSUE TITLE
Persistent token ?

### ISSUE THREAD

**Issue by daslicht** [ivankrastev26/pcloud-php-sdk#4]
Hi,
when I connect my app with pcloud its says : 

This code will expire after 600 seconds. 

Does that mean I needf to authorioze it again after each 600 seconds?

**Comment by mircobabini** [comment]
...the answer? :)

**Comment by mircobabini** [comment]
Seems like the answer is "no".

>  With the current implementation the access tokens given from pCloud API do not expire. 

source: https://docs.pcloud.com/methods/oauth_2.0/

**Comment by sich** [comment]
If you choose to use "code" oAuth 2.0 flow you have to exchange the code for access token in 600 sec. The access token that you will receive doesn't expire.
